### ISSUE TITLE
Неизвестная ошибка в ответ на NameError

### ISSUE THREAD

**Issue by FrCln** [wchistow/Errors-translater#1]
Ввод:
`NameError: name 'fkjj' is not defined`

Вывод:
```
В файле "ror: name 'fkjj' is not define", строке ror: name 'fkjj' is not define:
  Неизвестная ошибка
```

**Comment by wchistow** [comment]
Пока поддерживаются только полные трейбеки.

**Comment by wchistow** [comment]
Эта возмжность добавилась просто исправлением ошибки считывания при вводе пустой строки: bb6bab8
